name: Docker Build

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dev'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: dattito/purrmannplus-backend:test