name: Docker Buildx & Push

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      LATEST: "auto"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo 'LATEST=true' >> "$GITHUB_ENV"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dattito/purrmannplus-backend,ghcr.io/dattito/purrmannplus-backend
          tags: |
            type=ref,event=branch
          flavor: |
            latest=${{ env.LATEST}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push arm/64, arm/v7
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
