name: Docker Build

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dattito/purrmannplus-backend:$(date +%s)-ci